### PR TITLE
Corrected spelling on architecture / part 1 to 5

### PR DESCRIPTION
**Pull request by Cosmeeeen**
In response to [this issue](https://github.com/preslavmihaylov/booknotes/issues/2), corrected the spelling across all 5 documents using an adaptive spell checker, that also checks for context and manually making changes in order to confirm the right spelling. Would really appreciate a hacktoberfest-accepted if possible, otherwise I'm glad to help. 😄

### CODE REVIEW

**Comment by preslavmihaylov** [comment]
@Cosmeeeen the repo has the hacktoberfest topic attached to it, I believe that is sufficient?

I'll still add the label though, just in case

**Review by preslavmihaylov — APPROVED** [review]
Thanks a lot for this!

**Comment by preslavmihaylov** [comment]
@Cosmeeeen could you share what spellchecker you are using? I will consider integrating that with my writing workflow in the future :)

**Comment by Cosmeeeen** [comment]
> @Cosmeeeen could you share what spellchecker you are using? I will consider integrating that with my writing workflow in the future :)

Sure! I used [Grammarly](http://grammarly.com), which is a free browser extension + any online text editor. It has some errors on more complex grammar, and it isn't really adapted for more scientific texts, but if you manually correct every highlighted error you can get a really good result.

**Pull request merged**
